# Generated by Django 5.2.1 on 2025-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='route',
            field=models.CharField(max_length=10),
        ),
    ]
