name: 🚀 Deploy to EC2 on push to dep branch

on:
  push:
    branches:
      - dep

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.83.76.56 << 'EOF'
            cd ~/e20-3yp-Train-Tracking-and-Smart-Ticketing || exit 1

            # Clean local changes to avoid merge conflicts
            git reset --hard
            git clean -fd

            # Pull latest changes from dep branch
            git pull origin dep

            # Activate virtual environment
            rm -rf env
            python3 -m venv env
            source env/bin/activate

            # Upgrade pip and install dependencies
            pip install --upgrade pip
            pip install -r backend/requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
            
          EOF
